### ISSUE TITLE
Any Roadmap?

### ISSUE THREAD

**Issue by lobosan** [fauna-labs/fwitter#16]
Would be great to see this demo evolving frequently, it has a lot of potential.

Any plans to add these features "streaming, pagination, benchmarks, and a more advanced security model..."

**Comment by fauna-brecht** [comment]
Hey, 

thanks for the suggestion, we agree that those should be in there. We are currently doing some changes and currently are focusing our efforts on other areas. Give us some time to think about how and when to add these in.

**Comment by lobosan** [comment]
Hey, thanks for your response.

I think it would be useful to communicate these plans to the community, so we have an idea of where this is going, 
This could promote collaboration from users who want to do similar things.

**Comment by fauna-brecht** [comment]
Definitely, we'd have to think about those and come up with a plan in order not to overpromise. Thanks for the kind words on the potential of the repo.

**Comment by rts-rob** [comment]
We are currently working on a new flagship app that takes you from an empty folder/directory to a complete, productionized app. We're not getting rid of Fwitter, but we are directing efforts to support new features there.

Look for it to launch by October 31st!
