### ISSUE TITLE
error when build

### ISSUE THREAD

**Issue by vuau** [fauna-labs/fwitter#31]
```
> react-scripts build

Creating an optimized production build...
Failed to compile.

Can't find self.__WB_MANIFEST in your SW source.


npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fwitter@0.1.0 build: `react-scripts build`
npm ERR! Exit status 1
```
`npm start` working fine. I'm using node v12.22.1

**Comment by n400** [comment]
@vuau I just ran into this also. I added the following to the top of `service-worker.js` to fix it:

```
import {precacheAndRoute} from 'workbox-precaching';

if (process.env.NODE_ENV === 'production'){
  precacheAndRoute(self.__WB_MANIFEST);
}
```

**Comment by n400** [comment]
@vuau I got this working by completely deleting service-worker.js and the sw-related code from index.js so index.js now reads:
```
import React from 'react'
import ReactDOM from 'react-dom'

import App from './app'
// import * as serviceWorker from './service-worker'

import './styling/index.scss'

ReactDOM.render(<App />, document.getElementById('root'))
```

And I've also successfully deployed to Vercel w/o any issues by doing this.

**Comment by vuau** [comment]
@n400 I'm gonna build a PWA so I need the service worker

**Comment by rts-rob** [comment]
Per our comment on #16 - we're closing this repo to feature development.
